primary_audience = ["Young Adults", "Millennials"]
secondary_audience = ["Tech Enthusiasts", "Pop Culture Fans"]
industry = ["Tech & Software"]
product_service = ["Tech Products"]
best_platforms = ["Twitter (X)"]
humor_style = ["Relatable", "Satirical"]
emotion_targeted = ["Excitement", "Curiosity"]
engagement_type = ["Comment Bait"]
seasonality = ["Evergreen"]
tone_alignment = ["Playful", "Trendy"]
keywords_prompt = "We run a productivity app that helps users stay organized and get things done. It’s great for students, remote workers, and busy professionals. We want memes that highlight how frustrating staying productive can be and how our app makes it easier."
location = "Lahore, Pakistan"
language = "Urdu"
